theme: jekyll-theme-cayman

# testing some variables
header-heading-color: #00f
header-bg-color: #cceedd
header-bg-color-secondary: #155799

# Text
section-headings-color: #159957
body-text-color: #cc0000
body-link-color: #1e6bb8
blockquote-text-color: #819198

# Code
code-bg-color: #f3f6fa
code-text-color: #567482

# Borders
border-color: #dce6f0
table-border-color: #e9ebec
hr-border-color: #eff0f1
